# Generated by Django 5.2.1 on 2025-06-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0004_alter_follow_unique_together_retweet_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='count',
        ),
    ]
