# Generated by Django 5.2.1 on 2025-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0005_remove_like_count_remove_retweet_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='retweet',
            unique_together={('user', 'tweet')},
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='twitterApp.post')),
            ],
        ),
    ]
