# Generated by Django 5.2.3 on 2025-07-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0006_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(help_text='The user who is being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(help_text='The user who is following.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(help_text="The name of the hashtag (e.g., 'django').  Must be unique.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(help_text='The posts that use this hashtag.', related_name='hashtags', to='twitterApp.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='tweet',
            field=models.ForeignKey(help_text='The post that was liked.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twitterApp.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='The user who liked the post.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The content of the post (max 280 characters).', max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the post was created.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(help_text='The user who created the post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography about the user.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="The user's profile picture.", upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text="The user's personal website URL."),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(help_text='The post that was retweeted.', on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='twitterApp.post'),
        ),
        migrations.AlterField(
            model_name='retweet',
            name='user',
            field=models.ForeignKey(help_text='The user who retweeted the post.', on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
